### ISSUE TITLE
card component

### ISSUE THREAD

**Issue by Paulo-Augusto12** [Paulo-Augusto12/My-anime-list#2]
### Desenvolver o componente de card que está no design original

- [x] O componente precisa ter a imagem do anime
- [x] O componente precisa ter o nome do anime
- [x] O componente precisa informar a quantidade de episódios do anime

![Image](https://user-images.githubusercontent.com/102987686/235931246-890cff53-f5ea-492c-b21d-2856c80b7765.png)

**Comment by OttoCG** [comment]
Tempo de Conclusão :  01:54:15
